#!/usr/bin/env php
<?php

if(php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';


$app = new \Minicli\App([
    'app_path' => [
        __DIR__ . '/cli/Command',
    ],
    'theme' => '\Unicorn',
    'debug' => false,
], 'spacetraders');

$app->runCommand($argv);