#!/usr/bin/env php
<?php

if(php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$services = require __DIR__ . '/config/services.php';

\Phparch\SpaceTraders\ServiceContainer::config($services);

$app = new \Minicli\App([
    'app_path' => [
        __DIR__ . '/cli/Command',
    ],
    'theme' => '\Unicorn',
    'debug' => false,
], 'spacetraders');

$argv[1] = $argv[1] ?? 'help';

try {
    $app->runCommand($argv);
} catch (Throwable $e) {
    $app->error($e->getMessage());
}