name: 🐞 Bug Report
description: Report an unexpected error, incorrect behavior, or crash in the Spacetraders client application.
title: "[BUG] Concise summary of the issue"
labels: [ "bug", "triage", "needs-info" ]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following details  us to fix it quickly 
        and efficiently, please complete all sections below to 
        helps reproduce the issue faster.
  - type: textarea
    id: description
    attributes:
      label: Description of the Bug
      description: A clear and concise description of what the bug is and what you believe is happening.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide precise, minimal steps to reproduce the behavior.
        Example:
        1. Log in as a user with 'admin' role.
        2. Navigate to the '/settings/users' page.
        3. Click the 'Delete' button for user ID 42.
        4. See 500 Server Error.
      placeholder: Step-by-step instructions to trigger the bug.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A concise description of what actually happened, including any error messages you observed.
    validations:
      required: true

  - type: dropdown
    id: severity-suggestion
    attributes:
      label: Severity Suggestion
      description: How critical is this issue to the application's functionality? (This is a suggestion for the triage team)
      options:
        - Low (Cosmetic/UI issue)
        - Medium (Minor functionality issue)
        - High (Major feature is broken)
        - Critical (System is unusable or data loss)
    validations:
      required: true

  - type: dropdown
    id: browser-client
    attributes:
      label: Browser or Client
      description: Which browser or client were you using?
      options:
        - Chrome/Edge/Chromium
        - Firefox
        - Safari
        - Other (specify in context)

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      options:
        - Windows 11
        - macOS
        - Linux
        - Android
        - iOS
        - Other (specify in context)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Screenshots, Stack Traces)
      description: |
        If applicable, add screenshots, console errors, or other context.
        You can upload files directly to the issue.