name: Mess Detector Report
run-name: Run PHP Mess Detector
on: push

concurrency:
  group: wiki
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  Generate-PHPMD-Report:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: readline, curl, redis, mbstring, intl
          ini-values: max_memory=512M
          tools: composer, cs2pr, phpmd

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run PHPMD
        if: always()
        run: phpmd --ignore-violations-on-exit --ignore-errors-on-exit src,cli html phpmd.xml > phpmd.html

      - name: Convert HTML to Markdown
        id: html2markdown
        if: always()
        uses: rknj/html2markdown@v0.1.0
        with:
          html-file: "phpmd.html"

      - name: Upload report
        uses: int128/upload-artifact-wiki-action@v1
        id: phpmd-artifact
        with:
          path: phpmd.html

      - name: Show URL of wiki upload
        if: always()
        run: |
          cat ${{ steps.phpmd-artifact.outputs.url }}
